name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version:
          - 14
          - 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      # the "override" keyword was added in typescript@4.5.0
      # else, users can go down to typescript@3.8.x ("import type")
      - name: Install TypeScript 4.5
        run: npm i typescript@4.5
        if: ${{ matrix.node-version == '14' }}

      - name: Run tests
        run: npm test
